### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by rossmartin** [emin93/react-native-mapbox-navigation#2]
Thank you for your work on this. It was very helpful as a starting point and ideas for creating a react native wrapper. 

I have managed to create a barebones but fully working wrapper for Android/iOS here - https://github.com/homeeondemand/react-native-mapbox-navigation

Hopefully that can save you time and you can use this. PRs and improvements are certainly welcome as well!

**Comment by emin93** [comment]
Oh wow, great job! Added deprecation notice to `README.md`, let me know if you want to take the `react-native-mapbox-navigation` npm package name.
